name = "cdn"
main = "_worker.js"
compatibility_date = "2024-07-25"
compatibility_flags = ["nodejs_compat"]

[vars]
UUID = "550e8400-e29b-41d4-a716-446655440000"
PROXYIP = "proxy.xxxxxxxx.tk"
CDNIP = "www.visa.com.sg"
IP1 = "www.visa.com"
IP2 = "cis.visa.com"
IP3 = "africa.visa.com"
IP4 = "www.visa.com.sg"
IP5 = "www.visaeurope.at"
IP6 = "www.visa.com.mt"
IP7 = "qa.visamiddleeast.com"
IP8 = "usa.visa.com"
IP9 = "myanmar.visa.com"
IP10 = "www.visa.com.tw"
IP11 = "www.visaeurope.ch"
IP12 = "www.visa.com.br"
IP13 = "www.visasoutheasteurope.com"
PT1 = "80"
PT2 = "8080"
PT3 = "8880"
PT4 = "2052"
PT5 = "2082"
PT6 = "2086"
PT7 = "2095"
PT8 = "443"
PT9 = "8443"
PT10 = "2053"
PT11 = "2083"
PT12 = "2087"
PT13 = "2096"

[[env.production]]
name = "cdn-production"
